BASE_INSTRUCTIONS = """You will write a cover letter that reads like it was written by a thoughtful human, not generated by AI.

CRITICAL RULES — violating these makes the letter unusable:
- NEVER open with "I am excited/thrilled/pleased to apply"
- NEVER use: passionate, leverage, utilize, dynamic, innovative, synergy, results-driven, proven track record, fast-paced environment
- NEVER write perfectly balanced paragraphs of equal length
- NEVER start consecutive sentences with "I"
- NEVER summarize the resume — assume they will read it

WHAT TO DO INSTEAD:
- Open mid-thought, as if continuing a conversation or observation
- Use one specific, concrete detail from the JD to anchor the opening
- Let one paragraph be shorter than the others (even 1-2 sentences)
- Use a contraction or two (I've, I'd, that's) to loosen the tone
- If there's a number, make it feel earned — give it one sentence of context
- The closing should feel like a natural exit, not a formal bow

STRUCTURE:
- Opening: 2-3 sentences. Hook on something specific in the JD or company, then connect to yourself with are you currently doing and/or have done that relates to it.
- Body paragraph 1: One strong accomplishment with real context (why it was hard, what changed)
- Body paragraph 2: Why this company/role specifically — not just "your mission aligns with my values". Try to connect with somthing with my skills and interests from the resume.
- Closing: 2 sentences max. Low-pressure ask for a conversation

Keep it between 220-250 words of content and below 350 overall words. Slight imperfection in flow is fine — it reads more human.

Return ONLY valid JSON with this exact structure:
{
  "candidate_name": "Full name from resume",
  "candidate_email": "Email from resume",
  "candidate_phone": "Phone from resume or empty string",
  "candidate_address": "Address from resume (Mostly City and State) or empty string",
  "date": "Today's date in Month Day-th, Year format (e.g. June 1st, 2025)",
  "recipient_name": "Recipient name if in JD, else empty string",
  "recipient_title": "Prefferred Job title from the JD, or the Job title from the JD if no preferred title is given.",
  "company_name": "Company name from the JD",
  "company_address": "Company address if in JD, else empty string",
  "greeting": "Dear [Name] or Dear Hiring Manager",
  "opening_paragraph": "Hook-first opening, 2-3 sentences",
  "body_paragraphs": ["accomplishment paragraph", "company-fit paragraph"],
  "closing_paragraph": "Natural, low-pressure closing",
  "signature": "Candidate name"
}
"""

def build_cover_letter_prompt(md_resume: str, jd_text: str, style_hint: str) -> str:
    return f"""{BASE_INSTRUCTIONS}

STYLE DIRECTION:
{style_hint}

EXAMPLE OF BAD OPENING (do not write like this):
"I am excited to apply for the Software Engineer position at Acme Corp. With my proven track record in dynamic environments, I am confident I would be a valuable asset to your innovative team."

EXAMPLE OF GOOD OPENING (aim for this register):
"Most of my experience so far has been in university settings — tutoring, 
research assistance, a few career development workshops — but the problems 
[Company] is working on are exactly the kind I've been gravitating toward 
outside of class. When I came across this role, it felt less like a job 
posting and more like a description of where I want to spend the next few 
years figuring things out."

### Resume (Markdown)
{md_resume}

### Job Description
{jd_text}
"""
